[WARNING] [2020-06-07 11:56:04,260:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:04,277:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:06,281:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:08,284:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:10,288:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:12,291:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:14,294:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:16,297:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:18,301:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:20,304:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:22,307:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:24,310:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:26,313:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:28,316:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:30,320:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:32,323:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 11:56:34,326:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 12:14:15,666:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Memory Exception -- restart with less ensemle_nbest: 25
[WARNING] [2020-06-07 12:14:15,897:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Memory Exception -- restart with less ensemle_nbest: 12
[WARNING] [2020-06-07 12:14:16,191:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Memory Exception -- restart with less ensemle_nbest: 6
[WARNING] [2020-06-07 13:32:35,636:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Memory Exception -- restart with less ensemle_nbest: 3
[WARNING] [2020-06-07 13:32:35,882:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_56.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8740, 3) and data type float64

[WARNING] [2020-06-07 13:32:35,890:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_55.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 13:32:35,916:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_54.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,923:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_53.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,929:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_52.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,936:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_50.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,943:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_49.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,949:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_48.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,956:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_47.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,963:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_46.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,969:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_45.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,976:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_44.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,983:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_43.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,989:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_42.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:35,996:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_41.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,003:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_40.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,009:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_39.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,016:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_38.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,022:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_36.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,029:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_35.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,036:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_34.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,042:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_33.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,049:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_32.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,056:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_31.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,062:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_30.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,069:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_29.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,075:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_25.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,082:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_24.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,089:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_22.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,096:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_21.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,102:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_20.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,109:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_18.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,115:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_17.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,122:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_16.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,129:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_15.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,135:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_14.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,142:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_13.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,149:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_12.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,155:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_11.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,162:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_10.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,168:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_9.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,175:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_8.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,182:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_6.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,188:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_5.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,195:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_4.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,202:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_3.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,208:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_2.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:36,215:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,305:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_35.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,310:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_34.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,314:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_33.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,318:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_32.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,322:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_31.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,326:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_30.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,330:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_29.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,334:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_25.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,338:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_24.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,343:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_22.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,347:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_21.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,351:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_20.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,355:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_18.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,359:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_17.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,363:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_16.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,367:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_15.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,371:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_14.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,375:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_13.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,380:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_12.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,384:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_11.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,388:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_10.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,392:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_9.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,396:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_8.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,400:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_6.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,404:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_5.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,408:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_4.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,412:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_3.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,417:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_2.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:37,421:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,310:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_14.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,315:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_13.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,319:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_12.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,323:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_11.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,327:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_10.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,331:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_9.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,335:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_8.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,339:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_6.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,343:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_5.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,347:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_4.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,352:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_3.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,356:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_2.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-07 13:32:38,360:EnsembleBuilder(1):0d5bd1f0354c8b52fd903bae5caf1a88] Error loading /tmp/autosklearn_tmp_16198_3244/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

Log_loss score 0.11588419012841912
